//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.Hole = new HashSet<Hole>();
            this.Match = new HashSet<Match>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Web { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Hole> Hole { get; set; }
        public virtual ICollection<Match> Match { get; set; }
    }
}
