//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public Match()
        {
            this.Result = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public int TournamentId { get; set; }
        public int FieldId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsTournament { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Tournament Tournament { get; set; }
        public virtual ICollection<Result> Result { get; set; }
    }
}
