//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Result = new HashSet<Result>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string License { get; set; }
        public string Alias { get; set; }
        public string Phone { get; set; }
        public double RealHP { get; set; }
        public double GameHP { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Result> Result { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
