//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        public Tournament()
        {
            this.Match = new HashSet<Match>();
        }
    
        public int Id { get; set; }
        public int Year { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsFinished { get; set; }
    
        public virtual ICollection<Match> Match { get; set; }
    }
}
